remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
show_downloads: true
#########
title: Ngoc Nguyen
description: Modeling ecosystem carbon cycle and their interactions with climate 
theme: jekyll-theme-slate

# Navigation links
navigation:
  - name: About Me
    link: /about/
  - name: Research
    link: /research/
  - name: Outreach
    link: /outreach/
  - name: News
    link: /news/
