remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: Ngoc Nguyen
description: An Ecosystem Scientist studying interactions between climate and terrestrial ecosystem carbon fluxes
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
